#!/usr/bin/php
<?php

// Detect if running under Windows
define ("WINDOWS", strpos(strtoupper(PHP_OS),'WIN')!==false);

define ("HDRSIZE",5);

global $OF;

$ERR=false;

$ERR=parse_cmdline_args()!=0;

/*
 * Header format from zsound pcmplayer.asm:
 * size		.word	; 24bit digi size
 * sizehi	.byte	; ...
 * cfg		.byte	; VERA_audio_ctrl value
 * rate		.byte	; VERA_audio_rate
*/
$hdr  = array_fill(0,5,0);
$cfg  = BITRATE | STEREO | 0x0f; // 0x0f = max volume
$rate = (SAMPLERATE/(25000000>>16))+1;
$size = filesize(INFILENAME);

if(($rate > 0xFF)||($rate < 1)) {
	print "ERROR: Sample rate must be 1 .. 48828\n\n";
	exit(1);
}
$hdr[0]=$size & 0xff;
$hdr[1]=($size >> 8) & 0xff;
$hdr[2]=($size >> 16) & 0xff;
$hdr[3]=$cfg;
$hdr[4]=$rate;

$f = fopen(INFILENAME, "r");
if (! $f) {
  print "ERROR: Unable to open input file $filename\n";
  exit(1);
}
$pcm=fread($f,$size);
fclose($f);

$pcm = unpack(sprintf('C%d',$size),$pcm);
$pcm = array_values($pcm);

$f = fopen(OUTFILENAME, "wB");
fwrite($f,'zp',2);
fwrite($f,pack('C*',...$hdr));
fwrite($f,pack('C*',...$pcm));
fclose($f);


exit(0);

// =================================== END OF MAIN PROGRAM =============

function glob_windows_filenames($list) {
	$newlist = array();
	foreach ($list as $item) {
		$result = glob($item);
		if (sizeof($result) > 0)
			$newlist = $newlist + $result;
		else
			printf("WARNING: %s did not match any files\n",$item);
	}
	return($newlist);
}


function parse_cmdline_args() {
	global $argc;
	global $argv;

	$opts = getopt('hHsq', [], $rest_index);

	define ("USAGE","$argv[0] [-h] [-q] [-s] <rate> <input filename> [output filename]");

	if (isset($opts['h'])||isset($opts['H'])) {usage(); return(1);}
	
	if (!isset($argv[$rest_index])) {
		usage();
		print "ERROR: no sample rate specified.\n\n";
		return(1);
	} else {
		define("SAMPLERATE",$argv[$rest_index]);
	}
	
	if (!isset($argv[$rest_index+1])) {
		usage();
		print "ERROR: no input file specified.\n\n";
	} else {
		define("INFILENAME",$argv[$rest_index+1]);
	}
	
	if (isset($argv[$rest_index+2])) {
		define ("OUTFILENAME",$argv[$rest_index+2]);
	} else {
		// make this be infilename with ext changed to .zcm
		define ("OUTFILENAME","TEST.ZCM");
	}
	
	if (isset($opts['q'])) {
		define ("BITRATE",1<<5);
	} else {
		define ("BITRATE",0);
	}

	if (isset($opts['s'])) {
		define ("STEREO",1<<4);
	} else {
		define ("STEREO",0);
	}
	
	print "SUCCESS\n";
	return(0);
/*
 	if (isset($argv[$rest_index])) {
		$dmpfiles = array_slice($argv,$rest_index);
		if(WINDOWS) {
			$dmpfiles = glob_windows_filenames($dmpfiles);
		}
		$dmpfiles = deduplicate($dmpfiles);
	} else {
		shortusage("No input files specified.");
	}
*/

}

function usage($message = "") {
	global $argv;
	print "\nUSAGE:\n";
	print "  " . USAGE . "\n";
	print "\n";
	print "Help stuff goes here. ;)\n\n";
	if (strlen($message) > 0) {
		print "ERROR:\n  $message\n\n";
	}
	exit(1);
}




?>
